// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALk77LOw_-ZQMQrhGeCTIiW5o028VNiCc',
    appId: '1:277864273650:web:e7518c754ec0edca5c626b',
    messagingSenderId: '277864273650',
    projectId: 'social-network-66e3f',
    authDomain: 'social-network-66e3f.firebaseapp.com',
    databaseURL: 'https://social-network-66e3f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'social-network-66e3f.appspot.com',
    measurementId: 'G-920NWWCCLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu_mN84TDzqg5BEK56jsN6LfGb3qs8CgE',
    appId: '1:277864273650:android:2e040795add7a9015c626b',
    messagingSenderId: '277864273650',
    projectId: 'social-network-66e3f',
    databaseURL: 'https://social-network-66e3f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'social-network-66e3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc5a48F2FujL_WEBapMbn8ruBc-di8qe4',
    appId: '1:277864273650:ios:db48d3b0b48d37dc5c626b',
    messagingSenderId: '277864273650',
    projectId: 'social-network-66e3f',
    databaseURL: 'https://social-network-66e3f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'social-network-66e3f.appspot.com',
    iosBundleId: 'com.example.chatAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc5a48F2FujL_WEBapMbn8ruBc-di8qe4',
    appId: '1:277864273650:ios:719f35434a74d4f25c626b',
    messagingSenderId: '277864273650',
    projectId: 'social-network-66e3f',
    databaseURL: 'https://social-network-66e3f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'social-network-66e3f.appspot.com',
    iosBundleId: 'com.example.chatAppFlutter.RunnerTests',
  );
}
